# fly.toml file generated for late-moon-415 on 2020-12-14T00:48:55+07:00

[build]
builtin = "go"

[[services]]
internal_port = 8080
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["tls"]
port = "443"

[[services.tcp_checks]]
interval = 10000
timeout = 2000
